# Generated by Django 4.2 on 2023-04-11 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(db_index=False, max_length=72, unique=True, verbose_name='Слаг для URL')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Новостной пост',
                'verbose_name_plural': 'Новостные посты',
                'ordering': ('-pub_date', 'name'),
            },
        ),
    ]
